import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local'

// Theme Switcher components
import { ThemeProvider } from "next-themes";
import ScrollContext_Lenis from "@/providers/SmoothScrollContext_lenis";

// Local Fonts  
// 1. import, 2. add to body, 3. add to tailwind config
// 4. use as a className as. font-ogg-reg
const OggRegular = localFont({
  src: [
    {
      path: '../public/fonts/Ogg-Regular-BF646c18fc465e5.ttf',
    },
  ],
  variable: '--font-ogg-reg'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${OggRegular.variable} relative min-h-[100vh] cf2`}>
      
      <ScrollContext_Lenis>
      <ThemeProvider enableSystem={true} defaultTheme="system">
        {children}
        </ThemeProvider>
      </ScrollContext_Lenis>
      </body>
    </html>
  );
}
